"""fixed some errors

Revision ID: 24ba9e0dd0a5
Revises: 6d34195a7b36
Create Date: 2018-07-31 20:31:57.160347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ba9e0dd0a5'
down_revision = '6d34195a7b36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['process_id'], ['process.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('process_comments')
    # ### end Alembic commands ###
