"""Ver 5

Revision ID: 40e9f1c5bb28
Revises: 4514729bd3c8
Create Date: 2018-07-29 22:36:23.904614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40e9f1c5bb28'
down_revision = '4514729bd3c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process', sa.Column('final_approver', sa.String(length=20), nullable=True))
    op.drop_column('process', 'level')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process', sa.Column('level', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('process', 'final_approver')
    # ### end Alembic commands ###
