"""Ver 4.0

Revision ID: 4514729bd3c8
Revises: b5ba44093acb
Create Date: 2018-07-29 20:33:16.743185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4514729bd3c8'
down_revision = 'b5ba44093acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process', sa.Column('level', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('process', 'level')
    # ### end Alembic commands ###
