"""ver 2.0

Revision ID: 50ef95489e34
Revises: 976c24f82a1c
Create Date: 2018-07-27 19:16:41.918956

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50ef95489e34'
down_revision = '976c24f82a1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('permission', sa.String(length=20), nullable=True))
    op.drop_column('role', 'name')
    op.add_column('user', sa.Column('position', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'position')
    op.add_column('role', sa.Column('name', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('role', 'permission')
    # ### end Alembic commands ###
