"""add a initial_time property in Process model

Revision ID: 5e7a1f823012
Revises: 24ba9e0dd0a5
Create Date: 2018-07-31 20:45:21.872662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e7a1f823012'
down_revision = '24ba9e0dd0a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process', sa.Column('initial_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('process', 'initial_time')
    # ### end Alembic commands ###
