"""add a level property in Process

Revision ID: 6d34195a7b36
Revises: bc57df6ffb0c
Create Date: 2018-07-31 14:24:09.985596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d34195a7b36'
down_revision = 'bc57df6ffb0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process', sa.Column('level', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('process', 'level')
    # ### end Alembic commands ###
