"""add a real-name in User

Revision ID: 976c24f82a1c
Revises: 1b2d11b22cee
Create Date: 2018-07-27 18:22:17.297449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976c24f82a1c'
down_revision = '1b2d11b22cee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('real_name', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'real_name')
    # ### end Alembic commands ###
