"""add a 'stauts' property in Process model

Revision ID: a6354a1035e6
Revises: 5e7a1f823012
Create Date: 2018-07-31 21:03:25.497422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a6354a1035e6'
down_revision = '5e7a1f823012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process', sa.Column('status', sa.String(length=12), nullable=True))
    op.drop_column('process_comments', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process_comments', sa.Column('status', mysql.VARCHAR(length=12), nullable=True))
    op.drop_column('process', 'status')
    # ### end Alembic commands ###
