"""fixed some bugs in database

Revision ID: a876010a447a
Revises: 40e9f1c5bb28
Create Date: 2018-07-31 11:26:13.390746

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a876010a447a'
down_revision = '40e9f1c5bb28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('process', sa.Column('next_approver', sa.String(length=20), nullable=True))
    op.drop_column('process', 'approver')
    op.add_column('user', sa.Column('position_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'position', ['position_id'], ['id'])
    op.drop_column('user', 'position')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('position', mysql.VARCHAR(length=20), nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'position_id')
    op.add_column('process', sa.Column('approver', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('process', 'next_approver')
    op.drop_table('position')
    # ### end Alembic commands ###
