"""ver 3.0

Revision ID: b5ba44093acb
Revises: 50ef95489e34
Create Date: 2018-07-28 00:06:52.884540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5ba44093acb'
down_revision = '50ef95489e34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=256), nullable=True),
    sa.Column('contents', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('approver', sa.String(length=20), nullable=True),
    sa.Column('process_serial_num', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('process')
    # ### end Alembic commands ###
