"""delete some property in database

Revision ID: bc57df6ffb0c
Revises: a876010a447a
Create Date: 2018-07-31 11:34:07.164193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc57df6ffb0c'
down_revision = 'a876010a447a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('process', 'final_approver')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process', sa.Column('final_approver', mysql.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
